# 每日定时打包汉化文件
# Build Chinese localization patch daily

name: Chinese Patch Builder
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

env:
  GAME_VERSION: '0.3.2.1'
  PARATRANZ_PROJECT_ID: '6896'
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  LOG_LEVEL: 'DEBUG'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10" ]
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get current time
        id: time
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry  # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
        run: pipx install poetry

      - name: Set Up Python ${{ matrix.python-version }} and Dependents
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'

      - name: Initialize Project
        run: poetry install

      - name: Process the Chinese Localization Patch
        run: |
          poetry run python main.py

      - name: Capture the patch zip file
        uses: actions/upload-artifact@v4
        with:
          name: Chinese-Patch-${{ steps.date.outputs.date }}-${{ github.sha }}
          path: dist/*.zip
